In [1]:
import pandas as pd
from tqdm import tqdm

In [2]:
dataset_path        = 'data/processed/28714514_2021UKCensus_processed_20251009001.parquet'
shuffled_path       = 'data/processed/28714514_2021UKCensus_processed_20251009001rs.parquet'

In [3]:
ds = pd.read_parquet(dataset_path)
rs = pd.read_parquet(shuffled_path)

In [4]:
ds.head()

,uk001002_ntot_clipd_minmax,uk002002_ntot_noout_minmax,uk002003_ntot_noout_minmax,uk002004_ntot_clipd_minmax,uk002005_ntot_noout_minmax,uk002006_ntot_clipd_minmax,uk003002_ntot_noout_minmax,uk003003_ntot_noout_minmax,uk003005_ntot_noout_minmax,uk003006_ntot_noout_minmax,...,uk030005_ntot_clipd_ihs_minmax,uk030006_ntot_clipd_ihs_minmax,uk046004_ntot_clipd_ihs_minmax,uk046005_ntot_clipd_ihs_minmax,uk046009_ntot_clipd_ihs_minmax,uk046010_ntot_clipd_ihs_minmax,uk061006_ntot_clipd_ihs_minmax,uk062010_ntot_clipd_ihs_minmax,uk066008_ntot_clipd_ihs_minmax,uk066016_ntot_noout_ihs_minmax
OA,,,,,,,,,,,,,,,,,,,,,
E00000001,1.0,0.209183,0.640868,0.243536,0.169345,0.103164,0.366797,0.470588,0.601493,0.631579,...,0.285029,0.000000,0.310800,0.888200,0.000000,1.000000,0.000000,0.229715,0.000000,0.522534
E00000003,1.0,0.309635,0.645161,0.020326,0.081774,0.086102,0.251195,0.407407,0.656334,0.680556,...,0.345944,0.456294,0.000000,0.856471,0.000000,1.000000,0.000000,0.631733,0.112303,0.721809
E00000005,1.0,0.406816,0.426705,0.166442,0.186006,0.123386,0.418511,0.346154,0.550035,0.685714,...,0.175098,0.580362,0.000000,0.764779,0.540969,1.000000,0.387720,0.450933,0.218938,0.531674
E00000007,1.0,0.714259,0.224682,0.063464,0.056738,0.067209,0.436292,0.081081,0.493789,0.744186,...,0.378986,0.514418,0.542345,0.847968,0.000000,0.746280,0.270946,0.581465,0.000000,0.798493
E00000010,1.0,0.774129,0.182636,0.025794,0.092241,0.010926,0.760563,0.177083,0.193226,0.884615,...,0.337539,0.340955,0.418264,0.670164,0.000000,0.744087,0.000000,0.392793,0.144368,0.691696

In [5]:
rs.head()

,uk001002_ntot_clipd_minmax,uk002002_ntot_noout_minmax,uk002003_ntot_noout_minmax,uk002004_ntot_clipd_minmax,uk002005_ntot_noout_minmax,uk002006_ntot_clipd_minmax,uk003002_ntot_noout_minmax,uk003003_ntot_noout_minmax,uk003005_ntot_noout_minmax,uk003006_ntot_noout_minmax,...,uk030005_ntot_clipd_ihs_minmax,uk030006_ntot_clipd_ihs_minmax,uk046004_ntot_clipd_ihs_minmax,uk046005_ntot_clipd_ihs_minmax,uk046009_ntot_clipd_ihs_minmax,uk046010_ntot_clipd_ihs_minmax,uk061006_ntot_clipd_ihs_minmax,uk062010_ntot_clipd_ihs_minmax,uk066008_ntot_clipd_ihs_minmax,uk066016_ntot_noout_ihs_minmax
OA,,,,,,,,,,,,,,,,,,,,,
E00071085,1.000000,0.305556,0.572115,0.068917,0.215650,0.072985,0.152113,0.611111,0.814389,0.693878,...,0.000000,0.223937,0.427451,0.146423,0.000000,0.000000,0.000000,0.523080,0.478946,0.507327
E00177567,1.000000,0.633985,0.321839,0.050698,0.079320,0.032214,0.264544,0.166667,0.614839,0.666667,...,0.661007,0.356224,0.642472,0.428904,0.000000,0.609488,0.375846,0.509519,0.455178,0.626352
E00039966,1.000000,0.308138,0.661796,0.024641,0.121163,0.020876,0.172855,0.266667,0.827428,0.821918,...,0.000000,0.362560,0.000000,0.384673,0.000000,0.000000,0.000000,0.532128,0.340561,0.581545
E00155752,0.469484,0.400431,0.475673,0.109099,0.202043,0.059420,0.365070,0.222222,0.574783,0.724138,...,0.402945,0.073309,0.211627,0.683376,0.000000,0.307746,0.000000,0.566563,0.237234,0.685577
E00018981,1.000000,0.251574,0.710547,0.060628,0.054204,0.089890,0.175998,0.666667,0.715518,0.747126,...,0.827517,0.782768,0.000000,0.146423,0.699728,0.208073,0.176281,0.581465,0.289491,0.651806

In [6]:
ds.loc["E00001096"]

uk001002_ntot_clipd_minmax        1.000000
uk002002_ntot_noout_minmax        0.287947
uk002003_ntot_noout_minmax        0.522468
uk002004_ntot_clipd_minmax        0.065506
uk002005_ntot_noout_minmax        0.244017
                                    ...
uk046010_ntot_clipd_ihs_minmax    1.000000
uk061006_ntot_clipd_ihs_minmax    0.000000
uk062010_ntot_clipd_ihs_minmax    0.651151
uk066008_ntot_clipd_ihs_minmax    0.467440
uk066016_ntot_noout_ihs_minmax    0.644038
Name: E00001096, Length: 171, dtype: float64

In [7]:
rs.loc["E00001096"]

uk001002_ntot_clipd_minmax        1.000000
uk002002_ntot_noout_minmax        0.287947
uk002003_ntot_noout_minmax        0.522468
uk002004_ntot_clipd_minmax        0.065506
uk002005_ntot_noout_minmax        0.244017
                                    ...
uk046010_ntot_clipd_ihs_minmax    1.000000
uk061006_ntot_clipd_ihs_minmax    0.000000
uk062010_ntot_clipd_ihs_minmax    0.651151
uk066008_ntot_clipd_ihs_minmax    0.467440
uk066016_ntot_noout_ihs_minmax    0.644038
Name: E00001096, Length: 171, dtype: float64

In [8]:
assert ds.loc["E00001096"].equals(rs.loc["E00001096"]), f"OA E00001096 does not match between ds and rs"

In [9]:
oas = ds.index.to_list()

In [10]:
for oa in tqdm(oas):
    ds_oa = ds.loc[oa]
    rs_oa = rs.loc[oa]
    assert ds_oa.equals(rs_oa), f"OA {oa} does not match between ds and rs"

100%|██████████| 239023/239023 [00:27<00:00, 8824.68it/s]